//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurance2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insuree
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public bool DUI { get; set; }
        public int SpeedingTickets { get; set; }
        public bool CoverageType { get; set; }
        public decimal Quote { get; set; }

        //-----------------------------------------------------------------------------------------------------------------------


        public void getQuote()
        {
            double baseQuote = 50;

            // if age is 18-25 then add 25 to baseQuote

            var todayDate = DateTime.Now;
            var difference = todayDate.Year - DateOfBirth.Year;
            bool birthDayHasHappened;
            int age;

            if (DateOfBirth.Month > todayDate.Month)
            {
                birthDayHasHappened = false;
            }
            else
            {
                if (DateOfBirth.Month < todayDate.Month)
                {
                    birthDayHasHappened = true;
                }
                else
                {
                    if (DateOfBirth.Day <= todayDate.Day)
                    {
                        birthDayHasHappened = true;
                    }
                    else { birthDayHasHappened = false; }

                    
                }

            }
            if (birthDayHasHappened)
            {
                age = difference;
            }
            else 
            {
                age = difference - 1;
            }

            // todo calculate age

            if (age < 18 )
            {
                baseQuote = baseQuote + 100;
            }

            else
            {
                if (age < 25 || age > 100)
                {
                    baseQuote = baseQuote + 25;
                }
            }


                // todo carYear

                if (CarYear < 2000 || CarYear > 2015)
            {
                baseQuote = baseQuote + 25;
            }

            // todo carModel

            if (CarMake == "Porsche")
            {
                baseQuote = baseQuote + 25;
                if (CarModel == "911 Carrera")
                {
                    baseQuote = baseQuote + 25;
                }
            }



            // todo speedTickets

            baseQuote = baseQuote + (SpeedingTickets * 10);

            // todo DUI

            if (DUI)
            {
                baseQuote = baseQuote + (baseQuote * .25);
            }

            // todo fullCoverage

            if (CoverageType)
            {
                baseQuote = baseQuote + (baseQuote * .5);
            }

            Quote = (decimal)baseQuote;

        }
    }
}
